PREFIX base:  	<http://modelware.io/vocabularies/base#>
PREFIX mission: <http://modelware.io/vocabularies/mission#>
PREFIX project: <http://modelware.io/vocabularies/project#>
PREFIX system: 	<http://modelware.io/vocabularies/system#>

SELECT DISTINCT ?x ?y

WHERE {
	?x project:authorizes ?y ;
}