tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - openCAESAR.oml-luxor@0.8.2:o/sGt+9y2dbC0/b8p0Lyjw==