tasks:
  - init: cd vocabularies && ./gradlew build publishToMavenLocal && cd ../descriptions && ./gradlew build && cd ..

vscode:
  extensions:
    - openCAESAR.oml-luxor@0.8.2:o/sGt+9y2dbC0/b8p0Lyjw==